### ISSUE TITLE
Making answers more accurate

### ISSUE THREAD

**Issue by GammaUS** [subnub/Homework-helper#2]
Often when I used this tool answers don't pop up, the wrong information pops up,  etc. This can be solved by using quotation marks within the google search. This would be an example query

"Which of the following did Sherman Antitrust Act make illegal in 1890" site:quizlet.com

This would make it easier to find harder to search questions so the bot wouldn't mess up as often. Is this possible this can be added? I know it may be asking a lot. Again that is just an example question and is easy for the bot to search. I'm just asking that this be added to harder to find questions. 

Thank you.

**Comment by subnub** [comment]
Yeah that’s actually I really good idea, can’t believe I didn’t think of that lol. I will for sure look into adding or, or at the very least making it a setting. Thank you for the recommendation.

**Comment by GammaUS** [comment]
Sometimes it also shows the answer to the first question in the set instead of the question that was searched as well.

**Comment by GammaUS** [comment]
As an example if this error were to occur this is how it would look:

You search Which of the following did Sherman Antitrust Act make illegal in 1890 which would find https://quizlet.com/141905282/history-flash-cards/

It would instead show the answer as "It allows people to vote to accept or reject a law" which is the answer to the first question in the list "How does a referedum give people more influence in government?"
