### ISSUE TITLE
How Do You Get More Answers?

### ISSUE THREAD

**Issue by BigSalmon2** [subnub/Homework-helper#4]
Is there a way so that I could return answers even if they aren't a 100% match?

**Comment by Mattz-CE** [comment]
Under settings, there's a default list size

**Comment by BigSalmon2** [comment]
Can I edit the code to make the default list size larger, though?

**Comment by Mattz-CE** [comment]
It burns through ur free API token really fast but here's two ways to do it:
1. Under inspect, find the following and manually change.
```
<select id="options__select">
        <option value="1">1</option>
        <option value="3">3</option>
        <option value="5">5 (Default)</option>
        <option value="10">10</option>
        <option value="20">20</option>
```
2. Change the default value under [here](https://github.com/subnub/Homework-helper/blob/master/src/options.js) (line 53) and recompile it to google extension

**Comment by Mattz-CE** [comment]
Remember to close the issue
